version: 2.1

orbs:
  codacy: codacy/base@0.3.10
  codacy_plugins_test: codacy/plugins-test@0.2.2

jobs:
  publish_local:
    machine: true
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Publish tool docker locally
          command: sbt ";docker:stage;docker:publishLocal"
      - run:
          name: Save docker to file
          command: |
            mkdir -p workspace
            docker save --output ~/workdir/docker-image.tar codacy-engine-scalameta:latest
      - persist_to_workspace:
          root: ~/
          paths:
            - workdir/docker-image.tar

  publish:
    machine: true
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Load docker from file
          command: docker load --input ~/workdir/docker-image.tar
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag codacy-engine-scalameta codacy/$CIRCLE_PROJECT_REPONAME
            docker tag codacy-engine-scalameta codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)
            docker push codacy/$CIRCLE_PROJECT_REPONAME

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - codacy/checkout_and_version
      - codacy/sbt:
          name: build
          cmd: sbt compile
          requires:
            - codacy/checkout_and_version
      - publish_local:
          requires:
            - build
      - codacy_plugins_test/run:
          name: plugins_test
          docker_image_name: codacy-engine-scalameta
          requires:
            - publish_local
      - publish:
          context: CodacyDocker
          filters:
            branches:
              only: master
          requires:
            - plugins_test
      - codacy/tag_version:
          name: tag_version
          requires:
            - publish
