version: 2.1

orbs:
  codacy: codacy/base@0.0.13

jobs:
  publish_local:
    machine: true
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Publish tool docker locally
          command: sbt ";docker:stage;docker:publishLocal"
      - run:
          name: Save docker to file
          command: |
            mkdir -p workspace
            docker save --output workspace/docker.tar codacy-engine-scalameta:latest
      - persist_to_workspace:
          root: workspace
          paths:
            - docker.tar
  # TODO: switch to plugins_test orb
  plugins_test:
    machine: true
    working_directory: ~/
    steps:
      - run:
          name: Clone test project
          command: |
            (git -C ~/codacy-plugins-test fetch --all &&
              git -C ~/codacy-plugins-test reset --hard origin/master) ||
                git clone git://github.com/codacy/codacy-plugins-test.git ~/codacy-plugins-test
      - run:
          name: Generate cache key
          working_directory: ~/codacy-plugins-test
          command: |
            shasum build.sbt \
              project/plugins.sbt \
              project/build.properties \
              project/Common.scala \
              project/Dependencies.scala > /tmp/dependencies.cache.tmp
      - restore_cache:
          key: sbt-ivy2-dependencies-1.0.0-{{ checksum "/tmp/dependencies.cache.tmp" }}
      - run:
          name: Compile test project
          working_directory: ~/codacy-plugins-test
          command: sbt compile
      - save_cache:
          paths:
            - "~/.ivy2"
            - "~/.m2"
            - "~/.sbt"
            - "~/codacy-plugins-test/target"
            - "~/codacy-plugins-test/project/target"
            - "~/codacy-plugins-test/project/project"
          key: sbt-ivy2-dependencies-1.0.0-{{ checksum "/tmp/dependencies.cache.tmp" }}
      - attach_workspace:
          at: ~/
      - run:
          name: Load docker from file
          command: docker load --input docker.tar
      - run:
          name: Test json
          working_directory: ~/codacy-plugins-test
          command: sbt -Dcodacy.tests.ignore.descriptions=false "runMain codacy.plugins.DockerTest json codacy-engine-scalameta:latest"
      - run:
          name: Test patterns
          working_directory: ~/codacy-plugins-test
          command: sbt -Dcodacy.tests.noremove=false -Dcodacy.tests.threads=8 "runMain codacy.plugins.DockerTest pattern codacy-engine-scalameta:latest"
      - run:
          name: Test plugin
          working_directory: ~/codacy-plugins-test
          command: sbt "runMain codacy.plugins.DockerTest plugin codacy-engine-scalameta:latest"

  publish:
    machine: true
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Load docker from file
          command: docker load --input ~/docker.tar
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag codacy-engine-scalameta codacy/$CIRCLE_PROJECT_REPONAME
            docker tag codacy-engine-scalameta codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)
            docker push codacy/$CIRCLE_PROJECT_REPONAME

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - codacy/checkout_and_version
      - codacy/sbt:
          name: build
          cmd: sbt compile
          requires:
            - codacy/checkout_and_version
      - publish_local:
          requires:
            - build
      - plugins_test:
          requires:
            - publish_local
      - publish:
          context: CodacyDocker
          filters:
            branches:
              only: master
          requires:
            - plugins_test
      - codacy/tag_version:
          name: tag_version
          requires:
            - publish