version: 2.1

orbs:
  codacy: codacy/base@2.9.1
  codacy_plugins_test: codacy/plugins-test@0.10.6

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt:
          name: publish_docker_local
          cmd: |
            sbt "test;
                 set version in Docker := \"latest\";
                 docker:publishLocal"
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
      - codacy_plugins_test/run:
          name: plugins_test
          run_multiple_tests: true
          requires:
            - publish_docker_local
      - codacy/publish_docker:
          filters:
            branches:
              only: master
          requires:
            - publish_docker_local
            - plugins_test
      - codacy/sbt:
          name: publish_sonatype
          cmd: sbt retrieveGPGKeys core/publishSigned sonatypeBundleRelease
          filters:
            branches:
              only: master
          context: CodacyAWS
          requires:
            - publish_docker_local
            - plugins_test
      - codacy/tag_version:
          context: CodacyAWS
          requires:
            - codacy/publish_docker
            - publish_sonatype
