name: Comment issue on Jira

on:
  issue_comment:
    types: [created]

jobs:
  jira:
    env:
      JIRA_CREATE_COMMENT_AUTO: ${{ secrets.JIRA_CREATE_COMMENT_AUTO }}
    runs-on: ubuntu-latest
    steps:

      - name: Jira Login
        if: env.JIRA_CREATE_COMMENT_AUTO == 'true'
        id: login
        uses: atlassian/gajira-login@v2.0.0
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Extract Jira number
        if: env.JIRA_CREATE_COMMENT_AUTO == 'true'
        id: extract_jira_number
        uses: actions/github-script@v2.0.0
        env:
          JIRA_PROJECT: ${{ secrets.JIRA_PROJECT }}
          GITHUB_TITLE: ${{ github.event.issue.title }}
        with:
          script: |
            const jiraTaskRegex = new RegExp(`\\\[(${process.env.JIRA_PROJECT}-[0-9]+?)\\\]`)
            return process.env.GITHUB_TITLE.match(jiraTaskRegex)[1]
          result-encoding: string

      - name: Jira Add comment on issue
        if: env.JIRA_CREATE_COMMENT_AUTO == 'true'
        id: add_comment_jira_issue
        uses: atlassian/gajira-comment@v2.0.0
        with:
          issue: ${{ steps.extract_jira_number.outputs.result }}
          comment: |
            GitHub Comment : ${{ github.event.comment.user.login }}
            {quote}${{ github.event.comment.body }}{quote}
            ----
            {panel}
            _[Github permalink |${{ github.event.comment.html_url }}]_
            {panel}
